# Change these first
owner: 4heaton # Your GitHub organization or username, where this repository lives
repo: priv8-upptime # The name of this repository

assignees:
 - 4heaton
 - rmbolger

sites:
  - name: SoVoCal
    url: https://sovocal.org
    __dangerous__body_down: "KWQ8bcr"
  - name: Posh ACME
    url: https://poshac.me
    __dangerous__body_down: "KWQ8bcr"
  - name: 4Heaton
    url: https://4heaton.com
    __dangerous__body_down: "KWQ8bcr"
  - name: External DNS
    check: "tcp-ping"
    url: 47.181.77.90
    port: 53
  - name: Marion Net
    url: https://border.mrn.dvolve.net:49443

status-website:
  theme: dark
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.priv8.network
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Priv8 Network Upptime
  introTitle: Uptime Info
  introMessage: Uptime Info Message
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
